"""
Clustering Score Generator

Generates scoring scripts for clustering models.
"""

import os
from typing import Dict, List, Any


class ClusteringScoreGenerator:
    """Generates scoring scripts for clustering models."""
    
    def __init__(self, output_dir: str, user_id: str, model_id: str, model_literal: str):
        self.output_dir = output_dir
        self.user_id = user_id
        self.model_id = model_id
        self.model_literal = model_literal
        
        # Model type to class name mappings
        self.model_class_names = {
            'kmeans': 'KMeansClusteringScorer',
            'bisecting_kmeans': 'BisectingKMeansClusteringScorer'
        }
        
        # Model type to display name mappings
        self.model_display_names = {
            'kmeans': 'K-Means Clustering',
            'bisecting_kmeans': 'Bisecting K-Means Clustering'
        }
    
    def generate_scoring_code(self, config: Dict[str, Any], feature_vars: List[str],
                            selected_vars: List[str], categorical_vars: List[str],
                            numerical_vars: List[str], best_model_type: str):
        """Generate scoring code for clustering models."""
        print(f"📝 Generating clustering scoring code for {best_model_type}")
        
        # Get clustering configuration
        clustering_config = config.get('clustering', {})
        models_config = clustering_config.get('models', {})
        
        # Generate scripts for enabled model types
        model_types = ['kmeans', 'bisecting_kmeans']
        
        scripts_generated = 0
        for model_type in model_types:
            if models_config.get(f'run_{model_type}', False):
                self._generate_model_scoring_script(
                    model_type, config, feature_vars, selected_vars,
                    categorical_vars, numerical_vars
                )
                scripts_generated += 1
        
        if scripts_generated > 0:
            print(f"✅ Generated {scripts_generated} clustering scoring scripts in {self.output_dir}")
        else:
            print("⚠️  No clustering scoring scripts generated - no models were enabled")
    
    def _generate_model_scoring_script(self, model_type: str, config: Dict[str, Any],
                                     feature_vars: List[str], selected_vars: List[str],
                                     categorical_vars: List[str], numerical_vars: List[str]):
        """Generate scoring script for a specific clustering model type."""
        
        class_name = self.model_class_names.get(model_type, f'{model_type.title()}ClusteringScorer')
        display_name = self.model_display_names.get(model_type, f'{model_type.title()} Clustering')
        
        script_content = self._create_script_template(
            model_type, class_name, display_name, config,
            feature_vars, selected_vars, categorical_vars, numerical_vars
        )
        
        # Save the script
        script_filename = f"{model_type}_clustering_scorer.py"
        script_path = os.path.join(self.output_dir, script_filename)
        
        try:
            with open(script_path, 'w') as f:
                f.write(script_content)
            print(f"   📄 Generated: {script_filename}")
        except Exception as e:
            print(f"   ❌ Error generating {script_filename}: {str(e)}")
    
    def _create_script_template(self, model_type: str, class_name: str, display_name: str,
                               config: Dict[str, Any], feature_vars: List[str],
                               selected_vars: List[str], categorical_vars: List[str],
                               numerical_vars: List[str]) -> str:
        """Create the scoring script template for clustering models."""
        
        # Generate the script content
        script = f'''"""
{display_name} Model Scoring Script

This script provides clustering scoring functionality for the {model_type} model.
Generated by AutoML PySpark Package

Usage:
    scorer = {class_name}()
    cluster_results = scorer.score_data('path/to/new_data.csv')
"""

import os
import sys
import json
import pandas as pd
import numpy as np
from pyspark.sql import SparkSession
from pyspark.ml import PipelineModel
from pyspark.sql.functions import col, when, isnan, isnull, lit
from pyspark.sql.types import DoubleType
from pyspark.ml.clustering import KMeansModel, BisectingKMeansModel
from pyspark.ml.evaluation import ClusteringEvaluator

# Parameters
user_id = '{self.user_id}'
mdl_output_id = '{self.model_id}'
mdl_ltrl = '{self.model_literal}'

# Model variables - These will be loaded from model_info.json
SELECTED_VARS = {selected_vars}
CATEGORICAL_VARS = {categorical_vars}
NUMERICAL_VARS = {numerical_vars}
IMPUTE_VALUE = {config.get('impute_value', 0.0)}

class {class_name}:
    """
    {display_name} Model Scorer class for clustering new data.
    """
    
    def __init__(self, spark_session: SparkSession = None):
        """
        Initialize the clustering scorer.
        
        Args:
            spark_session: PySpark SparkSession (optional)
        """
        self.spark = spark_session or self._create_spark_session()
        self.preprocessing_pipeline = None
        self.clustering_model = None
        self.char_labels = None
        self.loaded = False
        
    def _create_spark_session(self) -> SparkSession:
        """Create PySpark session with optimized configuration for clustering scoring."""
        return SparkSession.builder \
            .appName("{display_name} Scorer") \
            .config("spark.driver.memory", "4g") \
            .config("spark.executor.memory", "4g") \
            .config("spark.sql.adaptive.enabled", "true") \
            .config("spark.sql.adaptive.coalescePartitions.enabled", "true") \
            .getOrCreate()
    
    def load_model(self, model_dir: str = "."):
        """
        Load the trained clustering model and preprocessing pipeline.
        
        Args:
            model_dir: Directory containing the saved model files
        """
        print(f"Loading {model_type} clustering model from {{model_dir}}")
        
        try:
            # Load categorical encoder first (consistent with regression/classification)
            encoder_path = os.path.join(model_dir, "char_labels")
            if os.path.exists(encoder_path):
                from pyspark.ml import PipelineModel
                self.char_labels = PipelineModel.load(encoder_path)
                print("   ✅ Categorical encoder loaded successfully")
            else:
                print(f"   ⚠️  Categorical encoder not found at {{encoder_path}}")
                print("   🔄 Will use basic categorical handling")
                self.char_labels = None
            
            # Load preprocessing pipeline
            pipeline_path = os.path.join(model_dir, "preprocessing_pipeline")
            if os.path.exists(pipeline_path):
                self.preprocessing_pipeline = PipelineModel.load(pipeline_path)
                print("   ✅ Preprocessing pipeline loaded successfully")
            else:
                print(f"   ⚠️  Preprocessing pipeline not found at {{pipeline_path}}")
                print("   🔄 Using basic preprocessing fallback")
            
            # Load clustering model
            model_path = os.path.join(model_dir, f"{model_type}_model")
            if os.path.exists(model_path):
                if "{model_type}" == "kmeans":
                    self.clustering_model = KMeansModel.load(model_path)
                elif "{model_type}" == "bisecting_kmeans":
                    self.clustering_model = BisectingKMeansModel.load(model_path)
                print(f"   ✅ {model_type} clustering model loaded")
            else:
                raise FileNotFoundError(f"Clustering model not found at {{model_path}}")
            
            self.loaded = True
            print("✅ Model loading completed")
            
        except Exception as e:
            print(f"❌ Error loading model: {{str(e)}}")
            raise
    
    def preprocess_data(self, data):
        """
        Apply preprocessing to new data.
        
        Args:
            data: Input DataFrame
            
        Returns:
            Preprocessed DataFrame with features column
        """
        if isinstance(data, str):
            # Load data from file path
            data = self.spark.read.csv(data, header=True, inferSchema=True)
        
        # First apply categorical encoding if available
        if self.char_labels:
            print("   🔄 Applying categorical encoding...")
            data = self.char_labels.transform(data)
            print("   ✅ Categorical encoding applied")
        
        # Then apply preprocessing pipeline if available
        if self.preprocessing_pipeline:
            processed_data = self.preprocessing_pipeline.transform(data)
        else:
            # Basic preprocessing fallback
            print("   Using basic preprocessing (no pipeline found)")
            
            # Select feature columns
            feature_cols = [col for col in data.columns if col in SELECTED_VARS]
            
            # Handle missing values
            for col_name in feature_cols:
                data = data.withColumn(col_name, 
                                     when(col(col_name).isNull() | isnan(col(col_name)), 
                                          lit(IMPUTE_VALUE)).otherwise(col(col_name)))
            
            # Create features vector (basic implementation)
            from pyspark.ml.feature import VectorAssembler
            assembler = VectorAssembler(inputCols=feature_cols, outputCol="features")
            processed_data = assembler.transform(data)
        
        return processed_data
    
    def score_data(self, input_data, output_path: str = None):
        """
        Score new data using the clustering model.
        
        Args:
            input_data: Input data (file path or DataFrame)
            output_path: Optional path to save results
            
        Returns:
            DataFrame with cluster assignments and metrics
        """
        if not self.loaded:
            raise ValueError("Model not loaded. Call load_model() first.")
        
        print("🔍 Scoring new data with clustering model...")
        
        # Preprocess the data
        print("   📊 Preprocessing data...")
        processed_data = self.preprocess_data(input_data)
        
        # Apply clustering
        print(f"   🤖 Applying {model_type} clustering...")
        cluster_results = self.clustering_model.transform(processed_data)
        
        # Calculate clustering metrics
        print("   📈 Calculating clustering metrics...")
        metrics = self._calculate_metrics(cluster_results)
        
        # Add cluster statistics
        cluster_summary = self._get_cluster_summary(cluster_results)
        
        # Show results summary
        print(f"\\n📊 Clustering Results Summary:")
        print(f"   • Total data points: {{cluster_results.count():,}}")
        print(f"   • Number of clusters: {{metrics.get('num_clusters', 'N/A')}}")
        print(f"   • Silhouette score: {{metrics.get('silhouette_score', 'N/A'):.4f}}")
        
        print(f"\\n🎯 Cluster Distribution:")
        cluster_summary.show()
        
        # Save results if requested
        if output_path:
            print(f"💾 Saving results to {{output_path}}")
            cluster_results.write.mode("overwrite").option("header", True).csv(output_path)
        
        return {{
            'cluster_assignments': cluster_results,
            'metrics': metrics,
            'cluster_summary': cluster_summary
        }}
    
    def _calculate_metrics(self, cluster_results):
        """Calculate clustering quality metrics."""
        try:
            evaluator = ClusteringEvaluator(featuresCol="features", predictionCol="prediction")
            silhouette_score = evaluator.evaluate(cluster_results)
            
            num_clusters = cluster_results.select("prediction").distinct().count()
            
            return {{
                'silhouette_score': silhouette_score,
                'num_clusters': num_clusters,
                'total_points': cluster_results.count()
            }}
        except Exception as e:
            print(f"   ⚠️  Could not calculate metrics: {{str(e)}}")
            return {{'silhouette_score': None, 'num_clusters': None}}
    
    def _get_cluster_summary(self, cluster_results):
        """Get summary statistics for each cluster."""
        return cluster_results.groupBy("prediction") \
            .count() \
            .withColumnRenamed("prediction", "cluster") \
            .withColumnRenamed("count", "num_points") \
            .orderBy("cluster")

# Example usage
if __name__ == "__main__":
    # Initialize scorer
    scorer = {class_name}()
    
    # Load the trained model
    # scorer.load_model("path/to/your/model/directory")
    
    # Score new data
    # results = scorer.score_data("path/to/your/new_data.csv")
    
    print("\\n💡 Usage Instructions:")
    print("1. Initialize the scorer: scorer = {class_name}()")
    print("2. Load your trained model: scorer.load_model('path/to/model')")
    print("3. Score new data: results = scorer.score_data('new_data.csv')")
    print("4. Access results: results['cluster_assignments'], results['metrics']")
'''
        
        return script 